apiVersion: v1
kind: Pod
metadata:
  name: spring-env
spec:
  containers:
  - name: my-container
    image: april0391/env-test
    imagePullPolicy: IfNotPresent
    envFrom:
    - configMapRef:
        name: spring-config
