apiVersion: v1
kind: Pod
metadata:
  name: configmap-example
spec:
  containers:
  - name: web-server
    image: nginx
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html  # 컨테이너 내에서의 마운트 경로
      readOnly: true
    - name: config
      mountPath: /etc/nginx/conf.d
      readOnly: true
  volumes:
  - name: html
    emptyDir: {}
  - name: config
    configMap:
      name: ttabae-config  # 사용할 ConfigMap 이름
      items:
      - key: nginx-config.conf
        path: nginx-config.conf

