supabase functions serve --env-file ./.env.local

# routing
npx uri-scheme open exp://10.238.179.174:8081/--/set-username --android

# sitemap
npx expo-router-sitemap


# invoke functions
curl -i -L \
  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0' \
  'http://localhost:54321/functions/v1/api/products'

curl -i -L \
  -X PUT \
  -H "Content-Type: application/json" \
  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjU0MzIxL2F1dGgvdjEiLCJzdWIiOiIwMWU4NjM0OS1mODc0LTQyM2UtODA5NS1jNTgyYmI1Y2FkZGEiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzU3ODU3NjEzLCJpYXQiOjE3NTc4NTQwMTMsImVtYWlsIjoidGVzdEB0ZXN0LmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiYXZhcmFyX3VybCI6IiIsImVtYWlsIjoidGVzdEB0ZXN0LmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJwaG9uZV92ZXJpZmllZCI6ZmFsc2UsInJvbGUiOiJzZWxsZXIiLCJzdWIiOiIwMWU4NjM0OS1mODc0LTQyM2UtODA5NS1jNTgyYmI1Y2FkZGEifSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTc1Nzg1NDAxM31dLCJzZXNzaW9uX2lkIjoiMTJkZGVhMzUtZTIwYS00MmRhLWFjMDUtOWY1ZWE5MmNkZTdlIiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.anVT9bfM_6uptkB6vLmr_LGEyoyYt2aSb6F73GyObQQ' \
  'http://localhost:54321/auth/v1/user' \
  -d '{"data":{"test":"value"}}'

curl -i -L \
  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjU0MzIxL2F1dGgvdjEiLCJzdWIiOiIxZGE2ZGM0Yi1iOTc3LTRhOTItOGI1ZS0zMTZkZTdiNzA4OTIiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzU3ODYzOTYzLCJpYXQiOjE3NTc4NjAzNjMsImVtYWlsIjoidEB0LmNvIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6eyJlbWFpbCI6InRAdC5jbyIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJpbml0X2RhdGEiOiIiLCJwaG9uZV92ZXJpZmllZCI6ZmFsc2UsInN1YiI6IjFkYTZkYzRiLWI5NzctNGE5Mi04YjVlLTMxNmRlN2I3MDg5MiJ9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzU3ODYwMzYzfV0sInNlc3Npb25faWQiOiI3ODU2OWI1Ny03NTY1LTQ3NjItODZiYi0zOGUyMzM2MjllZjYiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.IfN1xaUhTkVjkT3ZtAZ_pJKBH2iCOdXaTTKKpAxOt4I' \
  'http://localhost:54321/auth/v1/user'
  