apiVersion: v1
kind: Pod
metadata:
  name: pod-annotation
  annotations:
    builder: "hojun"
    buildDate: "20250119"
    imageregistry: "https://hub.docker.com/"
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80

