apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order-container
        image: order-service
        ports:
        - containerPort: 8080      # 컨테이너에서 사용하는 포트
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order
  ports:
    - protocol: TCP
      port: 80                   # 외부에 노출되는 포트
      targetPort: 8080           # 컨테이너에서 사용하는 포트
  type: ClusterIP
