apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: front-container
        image: front-app
        ports:
        - containerPort: 80      # 컨테이너에서 사용하는 포트
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: app-config
---
apiVersion: v1
kind: Service
metadata:
  name: front-service
spec:
  selector:
    app: front
  ports:
    - protocol: TCP
      port: 80                  # 외부에 노출되는 포트
      targetPort: 80            # 컨테이너에서 사용하는 포트
  type: ClusterIP
