spring:
  application:
    name: payment
  rabbitmq:
    host: localhost          # RabbitMQ ???
    port: 5672               # RabbitMQ ??
    username: guest          # ?? ??? ??
    password: guest          # ?? ????
server:
  port: 8081

rabbitmq:
  queue: order-queue         # ? ??
  exchange: order-exchange   # ????? ??
  routing-key: order-routing-key # ??? ?

order-serivce:
  url: http://localhost:8080