spring:
  application:
    name: jwt-advanced-yummi
  output:
    ansi:
      enabled: always

  datasource:
#    url: jdbc:h2:mem:db
    url: jdbc:h2:tcp://localhost/~/jwt-yummi
    driver-class-name: org.h2.Driver
    username: sa
    password:
  #    h2:
  #      console:
  #        enabled: true
  #        path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

  jwt:
    secret: abcd2wetfaergsadfg234gy35yhesmrtjh

logging:
  level:
    org.springframework.security: TRACE