create schema app;

set search_path to app;

create type user_role as enum (
  'buyer',
  'seller'
);

create table profiles (
  id uuid references auth.users(id) on delete cascade primary key,
  avatar_url text,
  role user_role not null
);

create table products (
  id int4 generated by default as identity primary key,
  seller_id uuid references app.profiles(id) on delete cascade,
  name text not null,
  description text,
  price int4 not null,
  image_url text
);

create table transactions (
  id uuid default gen_random_uuid() primary key,
  buyer_id uuid references app.profiles(id) not null,
  seller_id uuid references app.profiles(id) not null,
  amount int4 not null
);

insert into storage.buckets
  (id, name, public, file_size_limit, allowed_mime_types)
values
  ('avatars', 'avatars', true, 10485760, array['image/*']);
