apiVersion: v1
kind: Service
metadata:
  name: cluserip-service
spec:
  type: ClusterIP
  clusterIP: 10.43.100.100
  selector:
    app: webserver
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
