apiVersion: v1
kind: Service

metadata:
  name: nodeport-service

spec:
  type: NodePort          # Service의 종류
  clusterIP: 10.43.100.200
  selector:
    app: webserver 
  ports:
    - protocol: TCP       #  서비스에 접속하기 위한 프로토콜
      port: 80          # 쿠버네티스 내부에서 Service에 접속하기 위한 포트 번호
      targetPort: 80    # 매핑하기 위한 파드의 포트 번호
      nodePort: 30000     # 외부에서 사용자들이 접근하게 될 포트 번호
