server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:h2:mem:db
    driver-class-name: org.h2.Driver
    h2:
      console:
        enabled: true  # H2 ?? ???
        path: /h2-console  # ??? ??? URL (???? /h2-console)
    username: sa
    password:
  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

logging:
  level:
    org:
      springframework:
        security: TRACE